"""Language support and translation for Glacious."""

import langdetect
from functools import lru_cache

try:
    from deep_translator import GoogleTranslator
except Exception:
    GoogleTranslator = None

# All UI strings in 9 languages
UI_STRINGS = {
    "en": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Satellite-powered climate intelligence for Alpine journalism",
        "input_placeholder": "Ask a question or submit a claim about Alpine climate...",
        "mode_query_label": "Query mode — answering your question",
        "mode_validation_label": "Validation mode — checking your claim",
        "check_btn": "Check",
        "verdict_label": "Verdict",
        "confidence_label": "Confidence",
        "key_stat_label": "Key statistic",
        "summary_label": "Summary",
        "sources_label": "Sources & Credibility",
        "credibility_label": "Credibility Assessment",
        "accurate_finding_label": "Accurate Finding",
        "snow_cover_tab": "Snow & Ice",
        "glacier_tab": "Glaciers",
        "temperature_tab": "Climate",
        "permafrost_tab": "Permafrost & Soil",
        "biodiversity_tab": "Biodiversity",
        "economic_tab": "Economic Impact",
        "causes_label": "Causes & Context",
        "anthropogenic_label": "Human Factors",
        "ecological_label": "Ecological Outcomes",
        "social_label": "What This Means",
        "copy_btn": "Copy to clipboard",
        "report_btn": "Generate full report",
        "map_title": "Alpine Glacier Loss Map",
        "demo_mode_label": "📍 Demo mode active — using pre-loaded data",
        "language_select_label": "Language",
        "region_select_label": "Alpine Region",
        "year_range_label": "Year Range",
        "data_sources_label": "Data Sources",
        "about_label": "About Glacious",
        "supported": "Supported",
        "contradicted": "Contradicted",
        "partially_supported": "Partially Supported",
        "glaciers_lost": "Alpine glaciers lost",
        "temp_rise": "Temperature rise",
        "snow_days_lost": "Snow cover days lost",
        "permafrost_degrading": "Permafrost degrading",
        "since_1900": "Since 1900",
        "since_1880": "Since 1880",
        "average_trend": "Average trend",
        "at_10m_depth": "At 10m depth",
        "quick_examples": "Quick examples:",
        "climate_trends_title": "Alpine Climate Trends & Satellite Data",
        "glacier_decline_tab": "Glacier Decline",
        "satellite_map_tab": "Satellite Map",
        "climate_indicators_tab": "Climate Indicators",
        "streamline_map_tab": "Streamline Map",
        "satellite_map_header": "Satellite Map of Alpine Glacier Regions",
        "map_guide_label": "Map Guide",
        "map_guide_text": "Circle markers show glacier regions. Size indicates decline rate, color shows severity (green <15% | orange 15-30% | red >30%). Use map controls to toggle layers.",
        "heatmap_about_label": "About the Heatmap",
        "heatmap_about_text": "The glacier decline heatmap visualizes the intensity of ice loss across Alpine regions, with colors progressing from blue (minimal decline) to red (severe decline). This overlay helps identify climate hotspots where glaciers are retreating fastest.",
        "no_glacier_data": "No glacier data available!",
        "map_error": "Error loading map",
        "climate_metrics_header": "Key Alpine Climate Metrics",
        "climate_metrics_caption": "These indicators track the major climate changes affecting Alpine glaciers, snow cover, and permafrost stability since 2000.",
        "temp_metric_caption": "Average Alpine temperature increase since 1880",
        "snow_metric_caption": "Average annual snow season decline in Alpine regions",
        "permafrost_metric_caption": "Permafrost warming rate in deep mountain soil layers",
        "streamline_header": "Alpine Streamline Map",
        "streamline_caption": "Directional flow lines summarize regional glacier-stress movement patterns and help compare hotspots.",
        "streamline_title": "Regional Streamline Overview",
        "decline_label": "Decline",
        "start_year_label": "Start year",
        "end_year_label": "End year",
        "glacier_area_decline_title": "Glacier Area Decline by Alpine Region (2000-2024)",
        "region_axis_label": "Region",
        "glacier_area_axis_label": "Glacier Area (km²)",
        "decline_percent_short": "Decline %",
        "decline_percent_axis_label": "Decline %",
        "regional_decline_rate_title": "Regional Glacier Decline Rate (%)",
        "layer_satellite_default": "Satellite (Default)",
        "layer_osm": "OpenStreetMap",
        "layer_topographic": "Topographic",
        "layer_hillshade": "Hillshade Relief",
        "layer_heatmap": "Glacier Decline Heatmap",
        "layer_vegetation": "Vegetation Proxy",
        "veg_proxy_label": "vegetation proxy",
        "layer_glacier_regions": "Glacier Regions",
        "layer_streamlines": "Streamlines",
        "year_2000_label": "2000",
        "year_2024_label": "2024",
        "since_1980_delta": "-15% since 1980",
        "temperature_anomaly_series": "Temperature Anomaly (°C)",
        "snow_days_series": "Snow Days/Year",
        "climate_trends_chart_title": "Alpine Climate Trends (2000-2024)",
        "year_axis_label": "Year",
        "temperature_anomaly_axis": "Temperature Anomaly (°C)",
        "snow_days_axis": "Snow Days/Year",
        "analysis_results_header": "Analysis Results",
        "key_finding_label": "Key Finding",
        "root_causes_label": "Root Causes",
        "regional_global_drivers": "Regional & Global Drivers",
        "human_accelerators": "Human Accelerators",
        "consequences_label": "Consequences",
        "ecological_impacts": "Ecological Impacts",
        "social_economic": "Social & Economic",
        "unknown_label": "Unknown",
        "period_label": "Period",
        "details_label": "Details",
        "resolution_label": "Resolution",
        "coverage_label": "Coverage",
        "limitations_label": "Limitations",
        "similar_claims_warning": "Similar claims found in misinformation database - verify carefully",
        "data_visualizations_header": "Data Visualizations",
        "media_tab": "Media",
        "snow_cover_days_series": "Snow Cover Days",
        "snow_cover_duration_title": "Snow Cover Duration",
        "days_per_year_axis": "Days/Year",
        "glacier_area_series": "Glacier Area",
        "glacier_area_trend_title": "Glacier Area Trend",
        "area_axis_label": "Area (km²)",
        "temperature_anomaly_bar": "Temperature Anomaly",
        "temperature_anomaly_baseline_title": "Temperature Anomaly vs 1980-2010 Baseline",
        "anomaly_axis_label": "Anomaly (°C)",
        "temperature_10m_series": "Temperature at 10m",
        "permafrost_temp_trend_title": "Permafrost Temperature Trend",
        "temperature_axis_label": "Temperature (°C)",
        "species_elevation_shifts_title": "Alpine Species Elevation Shifts",
        "elevation_axis_label": "Elevation (m)",
        "ski_season_series": "Ski Season Length",
        "ski_season_title": "Alpine Ski Season Length",
        "days_axis_label": "Days",
        "media_placeholder": "Media coverage landscape and sentiment analysis would be displayed here.",
        "media_coming_soon": "GDELT and NewsAPI data integration coming soon.",
        "policy_guidance_tab": "Policy Guidance",
        "socioecological_impacts_tab": "Socioecological Impacts",
        "expected_implications": "Expected Implications",
        "policy_levers": "Policy Levers",
        "sector_water_supply": "Water Supply",
        "sector_energy": "Energy & Hydropower",
        "sector_infrastructure": "Infrastructure",
        "sector_economy": "Economy",
        "timetable_label": "Timetable",
        "emissions_pathways": "Emissions Pathways",
        "current_emissions": "Current Trajectory",
        "paris_aligned": "Paris-Aligned (< 2°C)",
        "adaptation_options": "Adaptation Options",
        "water_storage": "Water Storage & Management",
        "land_use_controls": "Land-Use Controls",
        "runoff_impacts": "Runoff Impacts",
        "surface_runoff": "Surface Runoff: Flood Risk & Infrastructure",
        "subsurface_flow": "Subsurface Flow: Groundwater & Water Supply",
        "seasonality_shift": "Seasonality Shift: Earlier Peak Flows",
        "flood_risk_impact": "Increased spring flooding risk",
        "summer_shortage": "Reduced summer water availability",
        "groundwater_recharge": "Delayed groundwater recharge",
        "peak_flow_shift": "Peak flows arriving 2–4 weeks earlier",
        "disaster_outcomes": "Alpine Hazards & Disaster Outcomes",
        "flooding_hazard": "Flooding (Rapid Melt Events)",
        "landslides_hazard": "Landslides & Debris Flows",
        "avalanches_hazard": "Avalanches (Wet Snow Dynamics)",
        "observed_trend": "Observed Trend",
        "recent_events": "Recent Notable Events",
        "trend_increasing": "Increasing",
        "trend_stable": "Stable",
        "trend_uncertain": "Uncertain",
        "economic_human_costs": "Economic & Human Costs",
        "infrastructure_damage": "Infrastructure Damage (roads, rail, hydropower)",
        "emergency_response": "Emergency Response & Recovery Costs",
        "displacement_label": "Displacement & Casualties",
        "risk_indicators": "Risk Indicators",
        "frequency_label": "Frequency",
        "severity_label": "Severity",
        "confidence_level": "Confidence Level",
        "severity_low": "Low",
        "severity_moderate": "Moderate",
        "severity_high": "High",
        "confidence_low": "Low",
        "confidence_medium": "Medium",
        "confidence_high": "High",
        "avg_damage_per_event": "Average Damage per Event",
        "glaciers_melting_data": "Satellite Data: Glaciers Melting",
        "snowpack_change_data": "Observation: Snowpack Changing",
        "permafrost_thaw_data": "Ground: Permafrost Thawing",
        "data_source_sentinel": "Sentinel-2 Satellite Imagery",
        "data_source_modis": "MODIS Snow Cover Data",
        "data_source_permos": "PERMOS (Permafrost Monitoring)",
        "data_source_eea": "European Environment Agency",
        "data_source_eurostat": "Eurostat Economic Data",
        "glacier_loss_label": "glacier loss",
        "generate_full_report": "Generate Full Report",
        "create_report_expander": "Create journalist-ready report",
        "report_language_label": "Report language",
        "format_label": "Format",
        "brief_label": "Brief",
        "technical_label": "Technical",
        "generate_report_btn": "Generate Report",
        "report_label": "Report",
        "download_txt_btn": "Download as .txt",
        "footer_line_1": "Satellite-powered climate intelligence for Alpine journalists.",
        "footer_line_2": "Data sources: Sentinel-2, MODIS, Landsat, GRACE, PERMOS, GBIF, Eurostat, and Alpine research centers.",
        "about_line_1": "is a satellite-powered climate analysis tool for Alpine journalists.",
        "about_line_2": "It answers climate questions and validates factual claims using multi-source satellite data, ground measurements, and scientific expertise. Every verdict includes source credibility assessment.",
        "across_8_countries": "across 8 Alpine countries",
        "placeholder_example_1": "How much snow cover has been lost in the Italian Alps in the past 10 years?",
        "placeholder_example_2": "Snow cover has receded by 10% in the last 2 years in the Swiss Alps. Is this true?",
        "placeholder_example_3": "What is happening to permafrost in the Austrian Alps?",
        "placeholder_example_4": "Are glaciers in the Dolomites melting faster than average?",
        "quick_label_snow_query": "Snow query",
        "quick_label_temp_claim": "Temperature claim",
        "quick_label_glacier_check": "Glacier check",
        "quick_example_snow_query": "How much snow cover has declined in the past decade?",
        "quick_example_temp_claim": "Is Alpine temperature warming faster than the global average?",
        "quick_example_glacier_check": "Have Swiss Alpine glaciers lost more than 25% since 2000?",
    },
    "de": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Satellitengestützte Klima-Intelligenz für Alpine Journalisten",
        "input_placeholder": "Stellen Sie eine Frage oder reichen Sie eine Behauptung über das Alpenklima ein...",
        "mode_query_label": "Abfragemodus — Beantwortung Ihrer Frage",
        "mode_validation_label": "Validierungsmodus — Überprüfung Ihrer Behauptung",
        "check_btn": "Prüfen",
        "verdict_label": "Urteil",
        "confidence_label": "Konfidenz",
        "key_stat_label": "Schlüsselstatistik",
        "summary_label": "Zusammenfassung",
        "sources_label": "Quellen & Glaubwürdigkeit",
        "credibility_label": "Glaubwürdigkeitsbewertung",
        "accurate_finding_label": "Genaue Feststellung",
        "snow_cover_tab": "Schnee & Eis",
        "glacier_tab": "Gletscher",
        "temperature_tab": "Klima",
        "permafrost_tab": "Permafrost & Boden",
        "biodiversity_tab": "Biodiversität",
        "economic_tab": "Wirtschaftliche Auswirkungen",
        "causes_label": "Ursachen & Kontext",
        "anthropogenic_label": "Menschliche Faktoren",
        "ecological_label": "Ökologische Auswirkungen",
        "social_label": "Was das bedeutet",
        "copy_btn": "In die Zwischenablage kopieren",
        "report_btn": "Vollständigen Bericht erstellen",
        "map_title": "Karte des Gletscherschwunds in den Alpen",
        "demo_mode_label": "📍 Demomodus aktiv — Verwendung vorgefüllter Daten",
        "language_select_label": "Sprache",
        "region_select_label": "Alpenregion",
        "year_range_label": "Jahresbereich",
        "data_sources_label": "Datenquellen",
        "about_label": "Über Glacious",
        "supported": "Unterstützt",
        "contradicted": "Widersprochen",
        "partially_supported": "Teilweise unterstützt",
        "glaciers_lost": "Gletscherfläche verloren",
        "temp_rise": "Temperaturgradient",
        "snow_days_lost": "Schneedeckentage verloren",
        "permafrost_degrading": "Permafrost degradiert",
        "policy_guidance_tab": "Politische Richtlinien",
        "socioecological_impacts_tab": "Sozialökologische Auswirkungen",
        "expected_implications": "Erwartete Auswirkungen",
        "policy_levers": "Politische Hebel",
        "sector_water_supply": "Wasserwirtschaft",
        "sector_energy": "Energie & Wasserkraft",
        "sector_infrastructure": "Infrastruktur",
        "sector_economy": "Wirtschaft",
        "timetable_label": "Zeitrahmen",
        "emissions_pathways": "Emissionspfade",
        "adaptation_options": "Anpassungsoptionen",
        "water_storage": "Wasserspeicher & Management",
        "land_use_controls": "Landnutzungskontrollen",
        "runoff_impacts": "Abflussauswirkungen",
        "surface_runoff": "Oberflächenabfluss: Hochwasserrisiko & Infrastruktur",
        "subsurface_flow": "Unterflächenabfluss: Grundwasser & Wasserversorgung",
        "seasonality_shift": "Saisonalitätsverschiebung: Frühere Spitzenstände",
        "disaster_outcomes": "Alpine Naturgefahren & Katastrophenergebnisse",
        "flooding_hazard": "Überschwemmungen (schnelle Schmelzereignisse)",
        "landslides_hazard": "Erdrutsche & Murgänge",
        "avalanches_hazard": "Lawinen (Nassschneedy namik)",
        "observed_trend": "Beobachteter Trend",
        "recent_events": "Jüngste bemerkenswerte Ereignisse",
        "economic_human_costs": "Wirtschaftliche & menschliche Kosten",
        "risk_indicators": "Risikoindikatoren",
    },
    "fr": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Intelligence climatique alimentée par satellite pour les journalistes alpins",
        "input_placeholder": "Posez une question ou soumettez une affirmation sur le climat alpin...",
        "mode_query_label": "Mode requête — répondre à votre question",
        "mode_validation_label": "Mode validation — vérifier votre affirmation",
        "check_btn": "Vérifier",
        "verdict_label": "Verdict",
        "confidence_label": "Confiance",
        "key_stat_label": "Statistique clé",
        "summary_label": "Résumé",
        "sources_label": "Sources et crédibilité",
        "credibility_label": "Évaluation de la crédibilité",
        "accurate_finding_label": "Résultat exact",
        "snow_cover_tab": "Neige et glace",
        "glacier_tab": "Glaciers",
        "temperature_tab": "Climat",
        "permafrost_tab": "Pergélisol et sol",
        "biodiversity_tab": "Biodiversité",
        "economic_tab": "Impact économique",
        "causes_label": "Causes et contexte",
        "anthropogenic_label": "Facteurs humains",
        "ecological_label": "Résultats écologiques",
        "social_label": "Ce que cela signifie",
        "copy_btn": "Copier dans le presse-papiers",
        "report_btn": "Générer un rapport complet",
        "map_title": "Carte de la perte de glaciers alpins",
        "demo_mode_label": "📍 Mode démo actif — utilisation de données préchargées",
        "language_select_label": "Langue",
        "region_select_label": "Région alpine",
        "year_range_label": "Plage d'années",
        "data_sources_label": "Sources de données",
        "about_label": "À propos de Glacious",
        "supported": "Soutenu",
        "contradicted": "Contredit",
        "partially_supported": "Partiellement soutenu",
        "glaciers_lost": "Surface glaciaire perdue",
        "temp_rise": "Gradient de température",
        "snow_days_lost": "Jours de couverture neigeuse perdus",
        "permafrost_degrading": "Pergélisol dégradant",
        "policy_guidance_tab": "Orientation politique",
        "socioecological_impacts_tab": "Impacts sociécologiques",
        "expected_implications": "Implications prévues",
        "policy_levers": "Leviers politiques",
        "sector_water_supply": "Approvisionnement en eau",
        "sector_energy": "Énergie & hydroélectricité",
        "sector_infrastructure": "Infrastructure",
        "sector_economy": "Économie",
        "timetable_label": "Calendrier",
        "emissions_pathways": "Trajectoires d'émissions",
        "adaptation_options": "Options d'adaptation",
        "water_storage": "Stockage & gestion de l'eau",
        "land_use_controls": "Contrôles d'utilisation des terres",
        "runoff_impacts": "Impacts du ruissellement",
        "surface_runoff": "Ruissellement de surface: risque d'inondation",
        "subsurface_flow": "Écoulement souterrain: eau souterraine",
        "seasonality_shift": "Décalage saisonnier: pics d'écoulement plus tôt",
        "disaster_outcomes": "Aléas alpins et résultats des catastrophes",
        "flooding_hazard": "Inondations (événements de fonte rapide)",
        "landslides_hazard": "Glissements & coulées de débris",
        "avalanches_hazard": "Avalanches (dynamique de neige mouillée)",
        "observed_trend": "Tendance observée",
        "recent_events": "Événements récents notables",
        "economic_human_costs": "Coûts économiques & humains",
        "risk_indicators": "Indicateurs de risque",
    },
    "it": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Intelligenza climatica alimentata da satellite per i giornalisti alpini",
        "input_placeholder": "Poni una domanda o invia un'affermazione sul clima alpino...",
        "mode_query_label": "Modalità query — rispondere alla tua domanda",
        "mode_validation_label": "Modalità validazione — verificare la tua affermazione",
        "check_btn": "Verifica",
        "verdict_label": "Verdetto",
        "confidence_label": "Confidenza",
        "key_stat_label": "Statistica chiave",
        "summary_label": "Riepilogo",
        "sources_label": "Fonti e credibilità",
        "credibility_label": "Valutazione della credibilità",
        "accurate_finding_label": "Risultato accurato",
        "snow_cover_tab": "Neve e ghiaccio",
        "glacier_tab": "Ghiacciai",
        "temperature_tab": "Clima",
        "permafrost_tab": "Permafrost e suolo",
        "biodiversity_tab": "Biodiversità",
        "economic_tab": "Impatto economico",
        "causes_label": "Cause e contesto",
        "anthropogenic_label": "Fattori umani",
        "ecological_label": "Risultati ecologici",
        "social_label": "Cosa significa",
        "copy_btn": "Copia negli appunti",
        "report_btn": "Genera report completo",
        "map_title": "Mappa della perdita di ghiacciai alpini",
        "demo_mode_label": "📍 Modalità demo attiva — utilizzo dati precaricati",
        "language_select_label": "Lingua",
        "region_select_label": "Regione alpina",
        "year_range_label": "Intervallo di anni",
        "data_sources_label": "Fonti di dati",
        "about_label": "Informazioni su Glacious",
        "supported": "Supportato",
        "contradicted": "Contraddetto",
        "partially_supported": "Parzialmente supportato",
        "glaciers_lost": "Superficie glaciale persa",
        "temp_rise": "Gradiente di temperatura",
        "snow_days_lost": "Giorni di copertura nevosa persi",
        "permafrost_degrading": "Permafrost in degradazione",
        "since_1900": "Dal 1900",
        "since_1880": "Dal 1880",
        "average_trend": "Tendenza media",
        "at_10m_depth": "A 10m di profondità",
        "quick_examples": "Esempi rapidi:",
        "climate_trends_title": "Tendenze climatiche alpine e dati satellitari",
        "glacier_decline_tab": "Riduzione dei ghiacciai",
        "satellite_map_tab": "Mappa satellitare",
        "climate_indicators_tab": "Indicatori climatici",
        "streamline_map_tab": "Mappa delle linee di flusso",
        "satellite_map_header": "Mappa satellitare delle regioni glaciali alpine",
        "map_guide_label": "Guida mappa",
        "map_guide_text": "I marcatori circolari mostrano le regioni glaciali. La dimensione indica il tasso di riduzione, il colore indica la severità (verde <15% | arancione 15-30% | rosso >30%). Usa i controlli mappa per attivare/disattivare i livelli.",
        "heatmap_about_label": "Informazioni sulla heatmap",
        "heatmap_about_text": "La heatmap della riduzione glaciale visualizza l'intensità della perdita di ghiaccio nelle regioni alpine, con colori dal blu (riduzione minima) al rosso (riduzione severa). Questo overlay aiuta a identificare gli hotspot climatici dove i ghiacciai si ritirano più rapidamente.",
        "no_glacier_data": "Nessun dato glaciale disponibile!",
        "map_error": "Errore nel caricamento della mappa",
        "climate_metrics_header": "Indicatori climatici chiave delle Alpi",
        "climate_metrics_caption": "Questi indicatori tracciano i principali cambiamenti climatici che influenzano ghiacciai, copertura nevosa e stabilità del permafrost nelle Alpi dal 2000.",
        "temp_metric_caption": "Aumento medio della temperatura alpina dal 1880",
        "snow_metric_caption": "Riduzione media annua della stagione nevosa nelle regioni alpine",
        "permafrost_metric_caption": "Tasso di riscaldamento del permafrost negli strati profondi del suolo montano",
        "streamline_header": "Mappa delle linee di flusso alpine",
        "streamline_caption": "Le linee di flusso direzionali riassumono i modelli regionali di stress glaciale e aiutano a confrontare gli hotspot.",
        "streamline_title": "Panoramica regionale delle linee di flusso",
        "decline_label": "Riduzione",
        "start_year_label": "Anno iniziale",
        "end_year_label": "Anno finale",
        "glacier_area_decline_title": "Riduzione dell'area glaciale per regione alpina (2000-2024)",
        "region_axis_label": "Regione",
        "glacier_area_axis_label": "Area glaciale (km²)",
        "decline_percent_short": "Riduzione %",
        "decline_percent_axis_label": "Riduzione %",
        "regional_decline_rate_title": "Tasso di riduzione glaciale regionale (%)",
        "layer_satellite_default": "Satellite (predefinito)",
        "layer_osm": "OpenStreetMap",
        "layer_topographic": "Topografica",
        "layer_hillshade": "Rilievo ombreggiato",
        "layer_heatmap": "Heatmap riduzione glaciale",
        "layer_vegetation": "Proxy vegetazione",
        "veg_proxy_label": "proxy vegetazione",
        "layer_glacier_regions": "Regioni glaciali",
        "layer_streamlines": "Linee di flusso",
        "year_2000_label": "2000",
        "year_2024_label": "2024",
        "since_1980_delta": "-15% dal 1980",
        "temperature_anomaly_series": "Anomalia di temperatura (°C)",
        "snow_days_series": "Giorni di neve/anno",
        "climate_trends_chart_title": "Tendenze climatiche alpine (2000-2024)",
        "year_axis_label": "Anno",
        "temperature_anomaly_axis": "Anomalia di temperatura (°C)",
        "snow_days_axis": "Giorni di neve/anno",
        "policy_guidance_tab": "Guida politica",
        "socioecological_impacts_tab": "Impatti socioecologici",
        "expected_implications": "Implicazioni previste",
        "policy_levers": "Leve politiche",
        "sector_water_supply": "Approvvigionamento idrico",
        "sector_energy": "Energia & Idroelettrico",
        "sector_infrastructure": "Infrastruttura",
        "sector_economy": "Economia",
        "timetable_label": "Cronologia",
        "emissions_pathways": "Percorsi di emissioni",
        "adaptation_options": "Opzioni di adattamento",
        "water_storage": "Stoccaggio & gestione dell'acqua",
        "land_use_controls": "Controlli sull'uso del suolo",
        "runoff_impacts": "Impatti del deflusso",
        "surface_runoff": "Deflusso superficiale: rischio alluvione",
        "subsurface_flow": "Flusso sotterraneo: acqua sotterranea",
        "seasonality_shift": "Cambiamento stagionale: picchi di flusso anticipati",
        "disaster_outcomes": "Pericoli alpini e risultati dei disastri",
        "flooding_hazard": "Inondazioni (eventi di fusione rapida)",
        "landslides_hazard": "Frane & colate di detrito",
        "avalanches_hazard": "Valanghe (dinamica della neve bagnata)",
        "observed_trend": "Tendenza osservata",
        "recent_events": "Eventi recenti notevoli",
        "economic_human_costs": "Costi economici & umani",
        "risk_indicators": "Indicatori di rischio",
    },
    "sl": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Satelitska klimatska obavještenja za alpske novinarje",
        "input_placeholder": "Postavite vprašanje ali predložite izjavo o alpskoj klimi...",
        "mode_query_label": "Način poizvedbe — odgovor na vaše vprašanje",
        "mode_validation_label": "Način preverjanja — preverka vaše izjave",
        "check_btn": "Provjeri",
        "verdict_label": "Presoja",
        "confidence_label": "Zaupanje",
        "key_stat_label": "Ključna statistika",
        "summary_label": "Povzetek",
        "sources_label": "Viri in verodostojnost",
        "credibility_label": "Ocena verodostojnosti",
        "accurate_finding_label": "Natančna ugotovitev",
        "snow_cover_tab": "Sneg in led",
        "glacier_tab": "Ledeniki",
        "temperature_tab": "Podnebje",
        "permafrost_tab": "Večno zmrznjeno tlo",
        "biodiversity_tab": "Biotska raznovrstnost",
        "economic_tab": "Gospodarski vpliv",
        "causes_label": "Vzroki in kontekst",
        "anthropogenic_label": "Dejavniki človeka",
        "ecological_label": "Ekološki rezultati",
        "social_label": "Kaj to pomeni",
        "copy_btn": "Kopiraj v odložišče",
        "report_btn": "Generiraj celoten poročilo",
        "map_title": "Zemljevid izgube alpskih ledenikov",
        "demo_mode_label": "📍 Демo način aktiven — uporaba predloženh podatkov",
        "language_select_label": "Jezik",
        "region_select_label": "Alpska regija",
        "year_range_label": "Obseg let",
        "data_sources_label": "Viri podatkov",
        "about_label": "O Glacious",
        "supported": "Podprto",
        "contradicted": "Zanikano",
        "partially_supported": "Delno podprto",
        "glaciers_lost": "Izgubljena površina ledenikov",
        "temp_rise": "Gradient temperature",
        "snow_days_lost": "Izgubljeni dnevi snežne pokrajine",
        "permafrost_degrading": "Degradacija večno zmrznjene zemljine",
        "since_1900": "Od leta 1900",
        "since_1880": "Od leta 1880",
        "average_trend": "Povprečni trend",
        "at_10m_depth": "Na globini 10 m",
        "quick_examples": "Hitri primeri:",
        "climate_trends_title": "Alpski podnebni trendi in satelitski podatki",
        "glacier_decline_tab": "Upad ledenikov",
        "satellite_map_tab": "Satelitski zemljevid",
        "climate_indicators_tab": "Podnebni kazalniki",
        "streamline_map_tab": "Zemljevid tokovnic",
        "satellite_map_header": "Satelitski zemljevid alpskih ledeniških regij",
        "map_guide_label": "Vodnik po zemljevidu",
        "map_guide_text": "Krožni označevalci prikazujejo ledeniške regije. Velikost prikazuje stopnjo upada, barva pa resnost (zeleno <15% | oranžno 15-30% | rdeče >30%). Za preklapljanje slojev uporabi kontrolnike zemljevida.",
        "heatmap_about_label": "O toplotnem zemljevidu",
        "heatmap_about_text": "Toplotni zemljevid upada ledenikov prikazuje intenzivnost izgube ledu po alpskih regijah, z barvami od modre (minimalen upad) do rdeče (hud upad). Ta sloj pomaga prepoznati podnebna žarišča, kjer se ledeniki umikajo najhitreje.",
        "no_glacier_data": "Podatki o ledenikih niso na voljo!",
        "map_error": "Napaka pri nalaganju zemljevida",
        "climate_metrics_header": "Ključni alpski podnebni kazalniki",
        "climate_metrics_caption": "Ti kazalniki prikazujejo glavne podnebne spremembe, ki od leta 2000 vplivajo na alpske ledenike, snežno odejo in stabilnost permafrosta.",
        "temp_metric_caption": "Povprečno zvišanje alpske temperature od leta 1880",
        "snow_metric_caption": "Povprečno letno skrajšanje snežne sezone v alpskih regijah",
        "permafrost_metric_caption": "Stopnja segrevanja permafrosta v globljih plasteh gorskih tal",
        "streamline_header": "Alpski zemljevid tokovnic",
        "streamline_caption": "Usmerjene tokovnice povzemajo regionalne vzorce ledeniškega stresa in pomagajo primerjati žarišča.",
        "streamline_title": "Regionalni pregled tokovnic",
        "decline_label": "Upad",
        "start_year_label": "Začetno leto",
        "end_year_label": "Končno leto",
        "glacier_area_decline_title": "Upad površine ledenikov po alpskih regijah (2000-2024)",
        "region_axis_label": "Regija",
        "glacier_area_axis_label": "Površina ledenika (km²)",
        "decline_percent_short": "Upad %",
        "decline_percent_axis_label": "Upad %",
        "regional_decline_rate_title": "Regionalna stopnja upada ledenikov (%)",
        "layer_satellite_default": "Satelit (privzeto)",
        "layer_osm": "OpenStreetMap",
        "layer_topographic": "Topografski",
        "layer_hillshade": "Senčen relief",
        "layer_heatmap": "Toplotni zemljevid upada ledenikov",
        "layer_vegetation": "Vegetacijski približek",
        "veg_proxy_label": "vegetacijski približek",
        "layer_glacier_regions": "Ledeniške regije",
        "layer_streamlines": "Tokovnice",
        "year_2000_label": "2000",
        "year_2024_label": "2024",
        "since_1980_delta": "-15% od leta 1980",
        "temperature_anomaly_series": "Temperaturna anomalija (°C)",
        "snow_days_series": "Snežni dnevi/leto",
        "climate_trends_chart_title": "Alpski podnebni trendi (2000-2024)",
        "year_axis_label": "Leto",
        "temperature_anomaly_axis": "Temperaturna anomalija (°C)",
        "snow_days_axis": "Snežni dnevi/leto",
        "analysis_results_header": "Rezultati analize",
        "key_finding_label": "Ključna ugotovitev",
        "root_causes_label": "Glavni vzroki",
        "regional_global_drivers": "Regionalni in globalni dejavniki",
        "human_accelerators": "Človeški pospeševalci",
        "consequences_label": "Posledice",
        "ecological_impacts": "Ekološki vplivi",
        "social_economic": "Družbeni in gospodarski",
        "unknown_label": "Neznano",
        "period_label": "Obdobje",
        "details_label": "Podrobnosti",
        "resolution_label": "Ločljivost",
        "coverage_label": "Pokritost",
        "limitations_label": "Omejitve",
        "similar_claims_warning": "V bazi dezinformacij so bile najdene podobne trditve - preverite zelo previdno",
        "data_visualizations_header": "Vizualizacije podatkov",
        "media_tab": "Mediji",
        "snow_cover_days_series": "Dnevi snežne odeje",
        "snow_cover_duration_title": "Trajanje snežne odeje",
        "days_per_year_axis": "Dni/leto",
        "glacier_area_series": "Površina ledenika",
        "glacier_area_trend_title": "Trend površine ledenikov",
        "area_axis_label": "Površina (km²)",
        "temperature_anomaly_bar": "Temperaturna anomalija",
        "temperature_anomaly_baseline_title": "Temperaturna anomalija glede na izhodišče 1980-2010",
        "anomaly_axis_label": "Anomalija (°C)",
        "temperature_10m_series": "Temperatura na 10 m",
        "permafrost_temp_trend_title": "Trend temperature permafrosta",
        "temperature_axis_label": "Temperatura (°C)",
        "species_elevation_shifts_title": "Višinski premiki alpskih vrst",
        "elevation_axis_label": "Nadmorska višina (m)",
        "ski_season_series": "Dolžina smučarske sezone",
        "ski_season_title": "Dolžina alpske smučarske sezone",
        "days_axis_label": "Dni",
        "media_placeholder": "Tukaj bi bil prikazan pregled medijskega poročanja in analiza sentimenta.",
        "media_coming_soon": "Integracija podatkov GDELT in NewsAPI bo kmalu na voljo.",
        "glacier_loss_label": "izguba ledenikov",
        "generate_full_report": "Ustvari celotno poročilo",
        "create_report_expander": "Ustvari poročilo, pripravljeno za novinarje",
        "report_language_label": "Jezik poročila",
        "format_label": "Oblika",
        "brief_label": "Kratek",
        "technical_label": "Tehnični",
        "generate_report_btn": "Ustvari poročilo",
        "report_label": "Poročilo",
        "download_txt_btn": "Prenesi kot .txt",
        "footer_line_1": "Satelitsko podprta podnebna inteligenca za alpske novinarje.",
        "footer_line_2": "Viri podatkov: Sentinel-2, MODIS, Landsat, GRACE, PERMOS, GBIF, Eurostat in alpski raziskovalni centri.",
        "policy_guidance_tab": "Politična usmeritev",
        "socioecological_impacts_tab": "Socialno-ekološki vplivi",
        "expected_implications": "Pričakovani učinki",
        "policy_levers": "Politični vzvodii",
        "sector_water_supply": "Oskrba z vodo",
        "sector_energy": "Energija & Hidroelektrika",
        "sector_infrastructure": "Infrastruktura",
        "sector_economy": "Gospodarstvo",
        "timetable_label": "Časovnica",
        "emissions_pathways": "Poti emisij",
        "adaptation_options": "Možnosti prilagoditve",
        "water_storage": "Skladiščenje vode & upravljanje",
        "land_use_controls": "Nadzor rabe tal",
        "runoff_impacts": "Vplivi toka",
        "surface_runoff": "Površinski tok: nevarnost poplave",
        "subsurface_flow": "Podpovršinski tok: podzemna voda",
        "seasonality_shift": "Sprememba sezonskih vplivov: zgodnejši vrhunci tokov",
        "disaster_outcomes": "Alpske nevarnosti in posledice nesreč",
        "flooding_hazard": "Poplave (dogodki hitrega taljenja)",
        "landslides_hazard": "Plazovi & masni premiki",
        "avalanches_hazard": "Plazovi (dinamika mokrega snega)",
        "observed_trend": "Opaženi trend",
        "recent_events": "Nedavni opazljivi dogodki",
        "economic_human_costs": "Ekonomski & človeški stroški",
        "risk_indicators": "Kazalniki tveganja",
    },
    "rm": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Intelligenza climatica alimentada da satellit per giornalists alpins",
        "input_placeholder": "La ina pregunta u submitescha ina pretenscha sur il clima alpin...",
        "mode_query_label": "Modus da dumonda — respunder a tia pregunta",
        "mode_validation_label": "Modus da validaziun — examinar tia pretenscha",
        "check_btn": "Controllà",
        "verdict_label": "Sentenza",
        "confidence_label": "Confidenza",
        "key_stat_label": "Statistica centrala",
        "summary_label": "Resumé",
        "sources_label": "Fontaunas e credibilitad",
        "credibility_label": "Evaluaziun da credibilitad",
        "accurate_finding_label": "Resultà exacta",
        "snow_cover_tab": "Niva e glassa",
        "glacier_tab": "Glatschers",
        "temperature_tab": "Clima",
        "permafrost_tab": "Sil parmanen congla e sil",
        "biodiversity_tab": "Diversitad da vidas",
        "economic_tab": "Impactus economics",
        "causes_label": "Causas e context",
        "anthropogenic_label": "Factors umans",
        "ecological_label": "Resultats ecologics",
        "social_label": "Tge che quai significa",
        "copy_btn": "Copiar a appunts",
        "report_btn": "Generescha rapport cumpleit",
        "map_title": "Maupa da perdittas da glatschers alpins",
        "demo_mode_label": "📍 Modus demo activ — utilisaziun da datas precargadas",
        "language_select_label": "Lingua",
        "region_select_label": "Regiun alpina",
        "year_range_label": "Perioda d'ons",
        "data_sources_label": "Fontaunas da datas",
        "about_label": "Davart Glacious",
        "supported": "Sustinut",
        "contradicted": "Contradît",
        "partially_supported": "Parzialmain sustinût",
        "glaciers_lost": "Superfitsch da glatscher perditga",
        "temp_rise": "Gradient da temperatura",
        "snow_days_lost": "Dis da cuorta da niva perditga",
        "permafrost_degrading": "Sil parmain congla in degradaziun",
        "policy_guidance_tab": "Orientaziun politica",
        "socioecological_impacts_tab": "Impachs socialo-ecologics",
        "expected_implications": "Implicaziuns spitgadas",
        "policy_levers": "Levers politics",
        "sector_water_supply": "Provista d'aua",
        "sector_energy": "Energia & Idroelectrica",
        "sector_infrastructure": "Infrastrucziun",
        "sector_economy": "Economia",
        "timetable_label": "Sche temporala",
        "emissions_pathways": "Vias da missiuns",
        "adaptation_options": "Opziuns da adaptaziun",
        "water_storage": "Stockaschi & administraziun d'aua",
        "land_use_controls": "Controllas da l'utilisaziun da terres",
        "runoff_impacts": "Impachs dal defless",
        "surface_runoff": "Defless da surfatscha: rischi da tgambada",
        "subsurface_flow": "Defless sut-surfatscha: aua sottenrrana",
        "seasonality_shift": "Spostament da stagiunalitad: pichs da defless inavant",
        "disaster_outcomes": "Periclals alpins e consequenzas da disasters",
        "flooding_hazard": "Tgambadas (eventua da fuschiun rapidla)",
        "landslides_hazard": "Plangadas & currents da detrius",
        "avalanches_hazard": "Avalantscha (dinamica da niva mudada)",
        "observed_trend": "Trend observà",
        "recent_events": "Events recent notaeivels",
        "economic_human_costs": "Costgas economicas & umanas",
        "risk_indicators": "Inditurs da rischi",
    },
    "hr": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Satelitska klimatska obavijest za alpske novinarima",
        "input_placeholder": "Postavite pitanje ili podnesi tvrdnju o alpskoj klimi...",
        "mode_query_label": "Režim upita — odgovor na vaše pitanje",
        "mode_validation_label": "Režim provjere — provjera vaše tvrdnje",
        "check_btn": "Provjeri",
        "verdict_label": "Presuda",
        "confidence_label": "Povjerenje",
        "key_stat_label": "Ključna statistika",
        "summary_label": "Sažetak",
        "sources_label": "Izvori i kredibilitet",
        "credibility_label": "Procjena kredibiliteta",
        "accurate_finding_label": "Tačan nalaz",
        "snow_cover_tab": "Snijeg i led",
        "glacier_tab": "Ledenjaci",
        "temperature_tab": "Klima",
        "permafrost_tab": "Trajni mraz i tlo",
        "biodiversity_tab": "Biološka raznolikost",
        "economic_tab": "Ekonomski utjecaj",
        "causes_label": "Uzroci i kontekst",
        "anthropogenic_label": "Ljudski čimbenici",
        "ecological_label": "Ekološki utjecaji",
        "social_label": "Što to znači",
        "copy_btn": "Kopiraj u međuspremnik",
        "report_btn": "Generiraj potpuni izvještaj",
        "map_title": "Karta gubitka alpskih ledenjaka",
        "demo_mode_label": "📍 Demo način aktivan — korištenje učitanih podataka",
        "language_select_label": "Jezik",
        "region_select_label": "Alpska regija",
        "year_range_label": "Raspon godina",
        "data_sources_label": "Izvori podataka",
        "about_label": "O Glacious",
        "supported": "Podržano",
        "contradicted": "Osporeno",
        "partially_supported": "Djelomično podržano",
        "glaciers_lost": "Izgubljena površina ledenjaka",
        "temp_rise": "Porast temperature",
        "snow_days_lost": "Izgubljeni dani snježnog pokrova",
        "permafrost_degrading": "Degradacija trajnog mraza",
        "policy_guidance_tab": "Smjernice politike",
        "socioecological_impacts_tab": "Socioekološki utjecaji",
        "expected_implications": "Očekivane implikacije",
        "policy_levers": "Politička poluga",
        "sector_water_supply": "Opskrba vodom",
        "sector_energy": "Energija & Hidroelektrika",
        "sector_infrastructure": "Infrastruktura",
        "sector_economy": "Gospodarstvo",
        "timetable_label": "Vremenski raspored",
        "emissions_pathways": "Putanje emisija",
        "adaptation_options": "Mogućnosti prilagodbe",
        "water_storage": "Skladištenje vode i upravljanje",
        "land_use_controls": "Kontrole korištenja zemlje",
        "runoff_impacts": "Utjecaji otjecanja",
        "surface_runoff": "Površinsko otjecanje: rizik od poplava",
        "subsurface_flow": "Podzemno otjecanje: podzemna voda",
        "seasonality_shift": "Pomak sezonalnosti: raniji vrhunci protoka",
        "disaster_outcomes": "Alpske opasnosti i posljedice katastrofe",
        "flooding_hazard": "Poplave (događaji brzog taljenja)",
        "landslides_hazard": "Klizišta i tokovi krhotina",
        "avalanches_hazard": "Lavine (dinamika vlažnog snijega)",
        "observed_trend": "Opaženi trend",
        "recent_events": "Nedavni značajni događaji",
        "economic_human_costs": "Ekonomski i ljudski troškovi",
        "risk_indicators": "Pokazatelji rizika",
    },
    "fur": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Inteligjenzie climatiche alimentade di satelit pai giornalists alpins",
        "input_placeholder": "Fâ une domande o presente une afirmaziun su la climz alpine...",
        "mode_query_label": "Modalitâ ricerche — rispuindi a la tô domande",
        "mode_validation_label": "Modalitâ validaziun — controle la tô afirmaziun",
        "check_btn": "Controlâ",
        "verdict_label": "Verdut",
        "confidence_label": "Confidanze",
        "key_stat_label": "Statiste clavê",
        "summary_label": "Somari",
        "sources_label": "Fonts e credibilitât",
        "credibility_label": "Valutaziun di credibilitât",
        "accurate_finding_label": "Risultât esât",
        "snow_cover_tab": "Nev e ghiaç",
        "glacier_tab": "Giaciârs",
        "temperature_tab": "Climat",
        "permafrost_tab": "Permafôst e tiere",
        "biodiversity_tab": "Biodiversitât",
        "economic_tab": "Impat economichis",
        "causes_label": "Cauzis e contest",
        "anthropogenic_label": "Factors umans",
        "ecological_label": "Risultats ecologjics",
        "social_label": "Tandi al significât",
        "copy_btn": "Copie in bufar",
        "report_btn": "Genere raport complet",
        "map_title": "Mape de perde dai giaciârs alpins",
        "demo_mode_label": "📍 Modalitâ demo ative — datis precarjis",
        "language_select_label": "Lenghe",
        "region_select_label": "Regjun alpine",
        "year_range_label": "Interval di agns",
        "data_sources_label": "Fonts di datis",
        "about_label": "Tanding a Glacious",
        "supported": "Sofuartît",
        "contradicted": "Contradît",
        "partially_supported": "Part sostinut",
        "glaciers_lost": "Superfice dai giaciârs perdue",
        "temp_rise": "Ament de temperature",
        "snow_days_lost": "Zencs di copierte di nev perdutz",
        "permafrost_degrading": "Degradaziun dal permafôst",
        "policy_guidance_tab": "Diretiv di politiche",
        "socioecological_impacts_tab": "Impats socio-ecologjics",
        "expected_implications": "Implicazions aspetadis",
        "policy_levers": "Tirants di politiche",
        "sector_water_supply": "Furniment d'aque",
        "sector_energy": "Energia & Idroeletrica",
        "sector_infrastructure": "Infrastrucure",
        "sector_economy": "Economie",
        "timetable_label": "Calendari",
        "emissions_pathways": "Viis di emissione",
        "adaptation_options": "Opzionis di adatament",
        "water_storage": "Deposit & gestion da aque",
        "land_use_controls": "Contruls d'ûs de tiere",
        "runoff_impacts": "Impats dal drenament",
        "surface_runoff": "Drenament di surfacie: risic di inondazion",
        "subsurface_flow": "Drenament sot-surfacie: aque sotteranade",
        "seasonality_shift": "Spostament da stagionalitât: pîcs di drenament anticipâts",
        "disaster_outcomes": "Pericals alpins e consequenzis di disastri",
        "flooding_hazard": "Inondazions (eventuals di fusionament velôz)",
        "landslides_hazard": "Franaments & torents di rosc",
        "avalanches_hazard": "Valanchis (dinamiche di nev molada)",
        "observed_trend": "Tendencie osservade",
        "recent_events": "Events rezents notevulis",
        "economic_human_costs": "Costis economichis & umans",
        "risk_indicators": "Indicaturs di risic",
    },
    "es": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Inteligencia de clima impulsada por satélite para periodistas de los Alpes",
        "input_placeholder": "Haz una pregunta o envía un reclamo sobre el clima alpino...",
        "check_btn": "Verificar",
        "analyze_btn": "Analizar",
        "language_select_label": "Idioma",
        "satellite_map_tab": "Mapa de satélite",
        "glacier_decline_tab": "Declive de glaciares",
        "climate_indicators_tab": "Indicadores climáticos",
        "policy_guidance_tab": "Orientación política",
        "socioecological_impacts_tab": "Impactos sociológicos",
        "about_label": "Acerca de Glacious",
        "verdict_label": "Veredicto",
        "confidence_label": "Confianza",
    },
    "pt": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Inteligência climática movida por satélite para jornalistas alpinos",
        "input_placeholder": "Faça uma pergunta ou envie uma alegação sobre o clima alpino...",
        "check_btn": "Verificar",
        "analyze_btn": "Analisar",
        "language_select_label": "Idioma",
        "satellite_map_tab": "Mapa de satélite",
        "glacier_decline_tab": "Declínio dos glaciares",
        "climate_indicators_tab": "Indicadores climáticos",
        "policy_guidance_tab": "Orientação política",
        "socioecological_impacts_tab": "Impactos socioeconômicos",
        "about_label": "Sobre Glacious",
        "verdict_label": "Veredito",
        "confidence_label": "Confiança",
    },
    "ru": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Спутниковая климатология для альпийских журналистов",
        "input_placeholder": "Задайте вопрос или подтвердите информацию об альпсикм климате...",
        "check_btn": "Проверить",
        "analyze_btn": "Анализировать",
        "language_select_label": "Язык",
        "satellite_map_tab": "Спутниковая карта",
        "glacier_decline_tab": "Сокращение ледников",
        "climate_indicators_tab": "Климатические показатели",
        "policy_guidance_tab": "Политические рекомендации",
        "socioecological_impacts_tab": "Социально-экологические последствия",
        "about_label": "О Glacious",
        "verdict_label": "Вердикт",
        "confidence_label": "Достоверность",
    },
    "zh": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "为高山记者提供的卫星气候智能",
        "input_placeholder": "提出问题或提交有关阿尔卑斯气候的声明...",
        "check_btn": "检查", 
        "analyze_btn": "分析",
        "language_select_label": "语言",
        "satellite_map_tab": "卫星地图",
        "glacier_decline_tab": "冰川衰退",
        "climate_indicators_tab": "气候指标",
        "policy_guidance_tab": "政策指导",
        "socioecological_impacts_tab": "社会生态后果",
        "about_label": "关于Glacious",
        "verdict_label": "判决",
        "confidence_label": "置信度",
    },
    "ja": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "アルパイン記者向けの衛星気候インテリジェンス",
        "input_placeholder": "アルプス気候に関する質問または主張を送信してください...",
        "check_btn": "チェック",
        "analyze_btn": "分析",
        "language_select_label": "言語",
        "satellite_map_tab": "衛星地図",
        "glacier_decline_tab": "氷河の衰退",
        "climate_indicators_tab": "気候指標",
        "policy_guidance_tab": "政策ガイダンス",
        "socioecological_impacts_tab": "社会生態学的影響",
        "about_label": "Glaciousについて",
        "verdict_label": "判定",
        "confidence_label": "信頼度",
    },
    "ar": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "ذكاء المناخ بقوة الأقمار الصناعية للصحفيين الألبينيين",  
        "input_placeholder": "اطرح سؤالاً أو قدم مطالبة حول المناخ الألبيني...",
        "check_btn": "التحقق",
        "analyze_btn": "تحليل",
        "language_select_label": "اللغة",
        "satellite_map_tab": "خريطة الأقمار الصناعية",
        "glacier_decline_tab": "تراجع الأنهار الجليدية",
        "climate_indicators_tab": "مؤشرات المناخ",
        "policy_guidance_tab": "إرشادات السياسة",
        "socioecological_impacts_tab": "التأثيرات الاجتماعية والبيئية",
        "about_label": "حول Glacious",
        "verdict_label": "الحكم",
        "confidence_label": "الثقة",
    },
    "ko": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "알파인 기자를 위한 위성 기후 인텔리전스",
        "input_placeholder": "알파인 기후에 대한 질문을 하거나 주장을 제시하세요...",
        "check_btn": "확인",
        "analyze_btn": "분석",
        "language_select_label": "언어",
        "satellite_map_tab": "위성 지도",
        "glacier_decline_tab": "빙하 감소",
        "climate_indicators_tab": "기후 지표",
        "policy_guidance_tab": "정책 지침",
        "socioecological_impacts_tab": "사회생태학적 영향",
        "about_label": "Glacious 정보",
        "verdict_label": "판정",
        "confidence_label": "신뢰도",
    },
    "nl": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Satelliet-aangedreven klimaatintelligentie voor Alpijse journalisten",
        "input_placeholder": "Stel een vraag of dien een claim in over het Alpijse klimaat...",
        "check_btn": "Verifiëren",
        "analyze_btn": "Analyseren",
        "language_select_label": "Taal",
        "satellite_map_tab": "Satellietkaart",
        "glacier_decline_tab": "Gletsjerteruggang",
        "climate_indicators_tab": "Klimaatindicatoren",
        "policy_guidance_tab": "Beleidsrichtlijn",
        "socioecological_impacts_tab": "Socio-ecologische gevolgen",
        "about_label": "Over Glacious",
        "verdict_label": "Uitspraak",
        "confidence_label": "Vertrouwen",
    },
    "pl": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Inteligencja klimatyczna wspierana satelitą dla dziennikarzy alpejskich",
        "input_placeholder": "Zadaj pytanie lub złóż twierdzenie na temat klimatu Alp...",
        "check_btn": "Weryfikuj",
        "analyze_btn": "Analizuj",
        "language_select_label": "Język",
        "satellite_map_tab": "Mapa satelitarna",
        "glacier_decline_tab": "Upadek lodowców",
        "climate_indicators_tab": "Wskaźniki klimatyczne",
        "policy_guidance_tab": "Wytyczne polityczne",
        "socioecological_impacts_tab": "Skutki społeczno-ekologiczne",
        "about_label": "O Glacious",
        "verdict_label": "Wyrok",
        "confidence_label": "Pewność",
    },
    "tr": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Alp gazetecileri için uydu destekli iklim istihbarı",
        "input_placeholder": "Alp iklimi hakkında bir soru sorun veya iddia gönder...",
        "check_btn": "Doğrula",
        "analyze_btn": "Analiz et",
        "language_select_label": "Dil",
        "satellite_map_tab": "Uydu haritası",
        "glacier_decline_tab": "Buzul Gerileşi",
        "climate_indicators_tab": "İklim göstergeleri",
        "policy_guidance_tab": "Politik rehberlik",
        "socioecological_impacts_tab": "Sosyo-ekolojik etkiler",
        "about_label": "Glacious Hakkında",
        "verdict_label": "Karar",
        "confidence_label": "Güven",
    },
    "hi": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "अल्पाइन पत्रकारों के लिए उपग्रह-संचालित जलवायु बुद्धिमत्ता",
        "input_placeholder": "अल्पाइन जलवायु के बारे में एक प्रश्न पूछें या दावा प्रस्तुत करें...",
        "check_btn": "सत्यापित करें",
        "analyze_btn": "विश्लेषण करें",
        "language_select_label": "भाषा",
        "satellite_map_tab": "उपग्रह मानचित्र",
        "glacier_decline_tab": "हिमनद गिरावट",
        "climate_indicators_tab": "जलवायु सूचक",
        "policy_guidance_tab": "नीति मार्गदर्शन",
        "socioecological_impacts_tab": "सामाजिक-पारिस्थितिक प्रभाव",
        "about_label": "Glacious के बारे में",
        "verdict_label": "निर्णय",
        "confidence_label": "विश्वास",
    },
    "sv": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Satellit-driven klimatintelligens för alpina journalister",
        "input_placeholder": "Ställ en fråga eller presentera ett påstående om Alpernas klimat...",
        "check_btn": "Verifiera",
        "analyze_btn": "Analysera",
        "language_select_label": "Språk",
        "satellite_map_tab": "Satellitskarta",
        "glacier_decline_tab": "Glaciärnedgång",
        "climate_indicators_tab": "Klimatindikatorer",
        "policy_guidance_tab": "Policyvägledning",
        "socioecological_impacts_tab": "Socio-ekologiska konsekvenser",
        "about_label": "Om Glacious",
        "verdict_label": "Dikt",
        "confidence_label": "Förtroende",
    },
    "no": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Satellitt-drevet klimaintelligens for alpine journalister",
        "input_placeholder": "Still et spørsmål eller fremlegg et påstand om alpint klima...",
        "check_btn": "Verifiser",
        "analyze_btn": "Analyser",
        "language_select_label": "Språk",
        "satellite_map_tab": "Satellittkart",
        "glacier_decline_tab": "Glaciernedgang",
        "climate_indicators_tab": "Klimaindikatorer",
        "policy_guidance_tab": "Policiveiledning",
        "socioecological_impacts_tab": "Sosio-økologiske konsekvenser",
        "about_label": "Om Glacious",
        "verdict_label": "Kjennelse",
        "confidence_label": "Tillit",
    },
    "da": {
        "app_title": "⛰ Glacious",
        "app_subtitle": "Satellitdrevet klimaintelligens for alpine journalister",
        "input_placeholder": "Stil et spørgsmål eller fremsæt en påstand om alpint klima...",
        "check_btn": "Bekræft",
        "analyze_btn": "Analyser",
        "language_select_label": "Sprog",
        "satellite_map_tab": "Satellittkort",
        "glacier_decline_tab": "Gletsjernedgang",
        "climate_indicators_tab": "Klimaindikatorer",
        "policy_guidance_tab": "Politischvejledning",
        "socioecological_impacts_tab": "Socialt-økologiske konsekvenser",
        "about_label": "Om Glacious",
        "verdict_label": "Dom",
        "confidence_label": "Tillid",
    },
}

# Scientific glossary in all languages
SCIENTIFIC_GLOSSARY = {
    "glacier": {
        "en": "Large persistent body of ice and snow that flows downslope under gravity",
        "de": "Großer persistenter Körper aus Eis und Schnee, der unter Schwerkraft abwärts fließt",
        "fr": "Large masse persistante de glace et de neige s'écoulant en aval sous la gravité",
        "it": "Grande massa persistente di ghiaccio e neve che scorre verso il basso sotto la gravità",
        "sl": "Velika trajnajoče masa ledu in snega, ki teče navzdol pod vplivom gravitacije",
        "rm": "Grond corp persistent d'atgliez e niva che fluiva sut cuntuorn",
        "hr": "Velika trajna masa leda i snijega koja teče niz nagib pod utjecajem gravitacije",
        "fur": "Masse grandt e durabile di ghiaç e nev che fluia in cale sut la fuarze di gravidât",
    },
    "NDSI": {
        "en": "Normalized Difference Snow Index - satellite metric measuring snow presence (0=no snow, 1=pure snow)",
        "de": "Normalisierter Differenzschneeindex - Satellitenmesswert zur Erfassung von Schneebestand",
        "fr": "Indice de Différence Normalisée de la Neige - mesure satellitaire de la présence de neige",
        "it": "Indice di Differenza Normalizzata della Neve - misura satellitare della presenza di neve",
        "sl": "Normaliziran različni indeks snega - satelitska meritev prisotnosti snega",
        "rm": "Indice Normalisà da Differenza da Niva - mesurada satellit da la presenzia da niva",
        "hr": "Normalizirani indeks razlike snijega - satelitska mjera prisutnosti snijega",
        "fur": "Indis di diferenze normalizà da nev - misurade satelit de la presenze di nev",
    },
    "albedo": {
        "en": "Fraction of sunlight reflected by a surface (snow has high albedo, glaciers lower)",
        "de": "Anteil des von einer Oberfläche reflektierten Sonnenlichts",
        "fr": "Fraction de la lumière solaire réfléchie par une surface",
        "it": "Frazione della luce solare riflessa da una superficie",
        "sl": "Delež sončne svetlobe, ki se odbije od površine",
        "rm": "Fracziun da sulegl rifletü d'ina superficie",
        "hr": "Udio sunčeve svjetlosti koji se odbija od površine",
        "fur": "Fraze de lus dal sole rifletude da une superficie",
    },
    "permafrost": {
        "en": "Ground that remains frozen for at least two consecutive years",
        "de": "Boden, der mindestens zwei aufeinanderfolgende Jahre gefroren bleibt",
        "fr": "Sol qui reste gelé pendant au moins deux ans consécutifs",
        "it": "Terreno che rimane congelato per almeno due anni consecutivi",
        "sl": "Tla, ki ostanejo zmrznjena najmanj dve zaporedni leti",
        "rm": "Tiera che resta cunglas per omnimain dus ons consecutivs",
        "hr": "Tlo koje ostaje zamrznjeno najmanje dvije uzastopne godine",
        "fur": "Tiere che reste congle par omnimancul dôs agns consecutîfs",
    },
    "snow_cover": {
        "en": "Area or duration of ground covered by snow at any time",
        "de": "Bereich oder Dauer der Schneebedeckung am Boden",
        "fr": "Zone ou durée du sol couvert de neige à tout moment",
        "it": "Area o durata del terreno coperto da neve in qualsiasi momento",
        "sl": "Območje ali trajanje tal pokritih s snegom v kateremkoli času",
        "rm": "Area u durada da terreno cuvert da niva",
        "hr": "Područje ili trajanje tla prekrivenog snijegom u bilo kojem trenutku",
        "fur": "Area u durade da terie cuarte da nev",
    },
    "anomaly": {
        "en": "Deviation from the long-term average (baseline) for a variable",
        "de": "Abweichung vom langfristigen Durchschnitt (Basislinie) für eine Variable",
        "fr": "Écart par rapport à la moyenne à long terme (valeur de référence) pour une variable",
        "it": "Deviazione dalla media a lungo termine (linea di base) per una variabile",
        "sl": "Odstopanje od dolgoročnega povprečja (izhodičča) za spremenljivko",
        "rm": "Deviziun dal media a lung termin (basala) per ina variabla",
        "hr": "Odstupanje od dugoročnog prosjeka (bazna linija) za varijablu",
        "fur": "Deviaziun dal media a lung termin (basale) par une variabile",
    },
    "baseline": {
        "en": "Reference period (typically 1980-2010 or historical average) used for comparison",
        "de": "Referenzzeitraum zur Vergleichbarkeit",
        "fr": "Période de référence utilisée pour la comparaison",
        "it": "Periodo di riferimento utilizzato per il confronto",
        "sl": "Referenčno obdobje, uporabljeno za primerjavo",
        "rm": "Perioda da referenza utilisada per comparaziun",
        "hr": "Referentno razdoblje korišteno za usporedbu",
        "fur": "Periude di referinze utilizade par confronto",
    },
    "phenology": {
        "en": "Timing of seasonal biological events (e.g., plant blooming, animal migration)",
        "de": "Zeitliche Abstimmung saisonaler biologischer Ereignisse",
        "fr": "Synchronisation des événements biologiques saisonniers",
        "it": "Sincronizzazione degli eventi biologici stagionali",
        "sl": "Čas pojava sezonskih bioloških dogodkov",
        "rm": "Temprada da eventualitads biologicas stagiunals",
        "hr": "Vremenski raspored sezonskih bioloških događaja",
        "fur": "Temperade dai eventualitats biologichis stagiunâls",
    },
    "mass_balance": {
        "en": "Annual change in glacier mass from accumulation minus ablation (mm water equivalent)",
        "de": "Jährliche Änderung der Gletschermasse",
        "fr": "Changement annuel de la masse glaciaire",
        "it": "Cambio annuale della massa glaciale",
        "sl": "Letna sprememba ledenikove mase",
        "rm": "Midada anuala da la massa da glatscher",
        "hr": "Godišnja promjena ledeničke mase",
        "fur": "Midade anuala de la masse dal giaciâr",
    },
    "moraine": {
        "en": "Unconsolidated rock and debris deposited by glacial action",
        "de": "Von Gletschertätigkeit abgelagertes Gestein und Trümmermaterial",
        "fr": "Roche et débris non consolidés déposés par l'action glaciaire",
        "it": "Roccia e detriti non consolidati depositati dall'azione glaciale",
        "sl": "Nekonsolidirana kamnina in ruševina odložena s poledenjem",
        "rm": "Silt e detri deposità da l'acziun da glatscher",
        "hr": "Nekonsolidirana stijena i detritus odloženi glacijalnom radnjom",
        "fur": "Silt e detri depositutz da l'aziun dai glaciârs",
    },
}

def t(key: str, lang: str) -> str:
    """Translate UI string key to target language."""
    if lang not in UI_STRINGS:
        lang = "en"
    if key in UI_STRINGS[lang]:
        return UI_STRINGS[lang][key]

    # Fallback to English for unknown keys.
    en_text = UI_STRINGS["en"].get(key, key)

    # Auto-translate missing keys at runtime so all supported sidebar languages
    # receive localized UI even when a key is newly added only in English.
    if lang != "en" and GoogleTranslator is not None and key in UI_STRINGS["en"]:
        translated = _translate_with_cache(en_text, lang)
        if translated:
            return translated

    return en_text


@lru_cache(maxsize=2048)
def _translate_with_cache(text: str, lang: str) -> str:
    """Translate English text to target language with lightweight caching."""
    if not text or GoogleTranslator is None:
        return text

    # Fallback mapping for language codes not supported directly by translator.
    target_map = {
        "en": "en",
        "de": "de",
        "fr": "fr",
        "it": "it",
        "sl": "sl",
        "hr": "hr",
        "rm": "it",   # best-effort fallback
        "fur": "it",  # best-effort fallback
    }

    target = target_map.get(lang, "en")
    if target == "en":
        return text

    try:
        return GoogleTranslator(source="en", target=target).translate(text)
    except Exception:
        return text

def detect_language(text: str) -> str:
    """Detect language from text using langdetect."""
    try:
        detected = langdetect.detect(text)
        # Map detected language codes to our supported languages
        lang_map = {
            "en": "en", "fr": "fr", "de": "de", "it": "it",
            "sl": "sl", "rm": "rm", "hr": "hr", "fur": "fur"
        }
        return lang_map.get(detected, "en")
    except:
        return "en"

def get_glossary_term(term: str, lang: str) -> str:
    """Get scientific glossary term definition in target language."""
    if lang not in SCIENTIFIC_GLOSSARY.get(term, {}):
        lang = "en"
    return SCIENTIFIC_GLOSSARY.get(term, {}).get(lang, term)
