"""Language support and translation for AlpineCheck."""

import langdetect

# All UI strings in 9 languages
UI_STRINGS = {
    "en": {
        "app_title": "⛰ AlpineCheck",
        "app_subtitle": "Satellite-powered climate intelligence for Alpine journalism",
        "input_placeholder": "Ask a question or submit a claim about Alpine climate...",
        "mode_query_label": "Query mode — answering your question",
        "mode_validation_label": "Validation mode — checking your claim",
        "analyze_btn": "Analyze",
        "verdict_label": "Verdict",
        "confidence_label": "Confidence",
        "key_stat_label": "Key statistic",
        "summary_label": "Summary",
        "sources_label": "Sources & Credibility",
        "credibility_label": "Credibility Assessment",
        "accurate_finding_label": "Accurate Finding",
        "snow_cover_tab": "Snow & Ice",
        "glacier_tab": "Glaciers",
        "temperature_tab": "Climate",
        "permafrost_tab": "Permafrost & Soil",
        "biodiversity_tab": "Biodiversity",
        "economic_tab": "Economic Impact",
        "causes_label": "Causes & Context",
        "anthropogenic_label": "Human Factors",
        "ecological_label": "Ecological Outcomes",
        "social_label": "What This Means",
        "copy_btn": "Copy to clipboard",
        "report_btn": "Generate full report",
        "map_title": "Alpine Glacier Loss Map",
        "demo_mode_label": "📍 Demo mode active — using pre-loaded data",
        "language_select_label": "Language",
        "region_select_label": "Alpine Region",
        "year_range_label": "Year Range",
        "data_sources_label": "Data Sources",
        "about_label": "About AlpineCheck",
        "supported": "Supported",
        "contradicted": "Contradicted",
        "partially_supported": "Partially Supported",
        "glaciers_lost": "Alpine glaciers lost",
        "temp_rise": "Temperature rise",
        "snow_days_lost": "Snow cover days lost",
        "permafrost_degrading": "Permafrost degrading",
    },
    "de": {
        "app_title": "⛰ AlpineCheck",
        "app_subtitle": "Satellitengestützte Klima-Intelligenz für Alpine Journalisten",
        "input_placeholder": "Stellen Sie eine Frage oder reichen Sie eine Behauptung über das Alpenklima ein...",
        "mode_query_label": "Abfragemodus — Beantwortung Ihrer Frage",
        "mode_validation_label": "Validierungsmodus — Überprüfung Ihrer Behauptung",
        "analyze_btn": "Analysieren",
        "verdict_label": "Urteil",
        "confidence_label": "Konfidenz",
        "key_stat_label": "Schlüsselstatistik",
        "summary_label": "Zusammenfassung",
        "sources_label": "Quellen & Glaubwürdigkeit",
        "credibility_label": "Glaubwürdigkeitsbewertung",
        "accurate_finding_label": "Genaue Feststellung",
        "snow_cover_tab": "Schnee & Eis",
        "glacier_tab": "Gletscher",
        "temperature_tab": "Klima",
        "permafrost_tab": "Permafrost & Boden",
        "biodiversity_tab": "Biodiversität",
        "economic_tab": "Wirtschaftliche Auswirkungen",
        "causes_label": "Ursachen & Kontext",
        "anthropogenic_label": "Menschliche Faktoren",
        "ecological_label": "Ökologische Auswirkungen",
        "social_label": "Was das bedeutet",
        "copy_btn": "In die Zwischenablage kopieren",
        "report_btn": "Vollständigen Bericht erstellen",
        "map_title": "Karte des Gletscherschwunds in den Alpen",
        "demo_mode_label": "📍 Demomodus aktiv — Verwendung vorgefüllter Daten",
        "language_select_label": "Sprache",
        "region_select_label": "Alpenregion",
        "year_range_label": "Jahresbereich",
        "data_sources_label": "Datenquellen",
        "about_label": "Über AlpineCheck",
        "supported": "Unterstützt",
        "contradicted": "Widersprochen",
        "partially_supported": "Teilweise unterstützt",
        "glaciers_lost": "Gletscherfläche verloren",
        "temp_rise": "Temperaturgradient",
        "snow_days_lost": "Schneedeckentage verloren",
        "permafrost_degrading": "Permafrost degradiert",
    },
    "fr": {
        "app_title": "⛰ AlpineCheck",
        "app_subtitle": "Intelligence climatique alimentée par satellite pour les journalistes alpins",
        "input_placeholder": "Posez une question ou soumettez une affirmation sur le climat alpin...",
        "mode_query_label": "Mode requête — répondre à votre question",
        "mode_validation_label": "Mode validation — vérifier votre affirmation",
        "analyze_btn": "Analyser",
        "verdict_label": "Verdict",
        "confidence_label": "Confiance",
        "key_stat_label": "Statistique clé",
        "summary_label": "Résumé",
        "sources_label": "Sources et crédibilité",
        "credibility_label": "Évaluation de la crédibilité",
        "accurate_finding_label": "Résultat exact",
        "snow_cover_tab": "Neige et glace",
        "glacier_tab": "Glaciers",
        "temperature_tab": "Climat",
        "permafrost_tab": "Pergélisol et sol",
        "biodiversity_tab": "Biodiversité",
        "economic_tab": "Impact économique",
        "causes_label": "Causes et contexte",
        "anthropogenic_label": "Facteurs humains",
        "ecological_label": "Résultats écologiques",
        "social_label": "Ce que cela signifie",
        "copy_btn": "Copier dans le presse-papiers",
        "report_btn": "Générer un rapport complet",
        "map_title": "Carte de la perte de glaciers alpins",
        "demo_mode_label": "📍 Mode démo actif — utilisation de données préchargées",
        "language_select_label": "Langue",
        "region_select_label": "Région alpine",
        "year_range_label": "Plage d'années",
        "data_sources_label": "Sources de données",
        "about_label": "À propos d'AlpineCheck",
        "supported": "Soutenu",
        "contradicted": "Contredit",
        "partially_supported": "Partiellement soutenu",
        "glaciers_lost": "Surface glaciaire perdue",
        "temp_rise": "Gradient de température",
        "snow_days_lost": "Jours de couverture neigeuse perdus",
        "permafrost_degrading": "Pergélisol dégradant",
    },
    "it": {
        "app_title": "⛰ AlpineCheck",
        "app_subtitle": "Intelligenza climatica alimentata da satellite per i giornalisti alpini",
        "input_placeholder": "Poni una domanda o invia un'affermazione sul clima alpino...",
        "mode_query_label": "Modalità query — rispondere alla tua domanda",
        "mode_validation_label": "Modalità validazione — verificare la tua affermazione",
        "analyze_btn": "Analizza",
        "verdict_label": "Verdetto",
        "confidence_label": "Confidenza",
        "key_stat_label": "Statistica chiave",
        "summary_label": "Riepilogo",
        "sources_label": "Fonti e credibilità",
        "credibility_label": "Valutazione della credibilità",
        "accurate_finding_label": "Risultato accurato",
        "snow_cover_tab": "Neve e ghiaccio",
        "glacier_tab": "Ghiacciai",
        "temperature_tab": "Clima",
        "permafrost_tab": "Permafrost e suolo",
        "biodiversity_tab": "Biodiversità",
        "economic_tab": "Impatto economico",
        "causes_label": "Cause e contesto",
        "anthropogenic_label": "Fattori umani",
        "ecological_label": "Risultati ecologici",
        "social_label": "Cosa significa",
        "copy_btn": "Copia negli appunti",
        "report_btn": "Genera report completo",
        "map_title": "Mappa della perdita di ghiacciai alpini",
        "demo_mode_label": "📍 Modalità demo attiva — utilizzo dati precaricati",
        "language_select_label": "Lingua",
        "region_select_label": "Regione alpina",
        "year_range_label": "Intervallo di anni",
        "data_sources_label": "Fonti di dati",
        "about_label": "Informazioni su AlpineCheck",
        "supported": "Supportato",
        "contradicted": "Contraddetto",
        "partially_supported": "Parzialmente supportato",
        "glaciers_lost": "Superficie glaciale persa",
        "temp_rise": "Gradiente di temperatura",
        "snow_days_lost": "Giorni di copertura nevosa persi",
        "permafrost_degrading": "Permafrost in degradazione",
    },
    "sl": {
        "app_title": "⛰ AlpineCheck",
        "app_subtitle": "Satelitska klimatska obavještenja za alpske novinarje",
        "input_placeholder": "Postavite vprašanje ali predložite izjavo o alpskoj klimi...",
        "mode_query_label": "Način poizvedbe — odgovor na vaše vprašanje",
        "mode_validation_label": "Način preverjanja — preverka vaše izjave",
        "analyze_btn": "Analiziraj",
        "verdict_label": "Presoja",
        "confidence_label": "Zaupanje",
        "key_stat_label": "Ključna statistika",
        "summary_label": "Povzetek",
        "sources_label": "Viri in verodostojnost",
        "credibility_label": "Ocena verodostojnosti",
        "accurate_finding_label": "Natančna ugotovitev",
        "snow_cover_tab": "Sneg in led",
        "glacier_tab": "Ledeniki",
        "temperature_tab": "Podnebje",
        "permafrost_tab": "Večno zmrznjeno tlo",
        "biodiversity_tab": "Biotska raznovrstnost",
        "economic_tab": "Gospodarski vpliv",
        "causes_label": "Vzroki in kontekst",
        "anthropogenic_label": "Dejavniki človeka",
        "ecological_label": "Ekološki rezultati",
        "social_label": "Kaj to pomeni",
        "copy_btn": "Kopiraj v odložišče",
        "report_btn": "Generiraj celoten poročilo",
        "map_title": "Zemljevid izgube alpskih ledenikov",
        "demo_mode_label": "📍 Демo način aktiven — uporaba predloženh podatkov",
        "language_select_label": "Jezik",
        "region_select_label": "Alpska regija",
        "year_range_label": "Obseg let",
        "data_sources_label": "Viri podatkov",
        "about_label": "O AlpineCheck",
        "supported": "Podprto",
        "contradicted": "Zanikano",
        "partially_supported": "Delno podprto",
        "glaciers_lost": "Izgubljena površina ledenikov",
        "temp_rise": "Gradient temperature",
        "snow_days_lost": "Izgubljeni dnevi snežne pokrajine",
        "permafrost_degrading": "Degradacija večno zmrznjene zemljine",
    },
    "rm": {
        "app_title": "⛰ AlpineCheck",
        "app_subtitle": "Intelligenza climatica alimentada da satellit per giornalists alpins",
        "input_placeholder": "La ina pregunta u submitescha ina pretenscha sur il clima alpin...",
        "mode_query_label": "Modus da dumonda — respunder a tia pregunta",
        "mode_validation_label": "Modus da validaziun — examinar tia pretenscha",
        "analyze_btn": "Analisar",
        "verdict_label": "Sentenza",
        "confidence_label": "Confidenza",
        "key_stat_label": "Statistica centrala",
        "summary_label": "Resumé",
        "sources_label": "Fontaunas e credibilitad",
        "credibility_label": "Evaluaziun da credibilitad",
        "accurate_finding_label": "Resultà exacta",
        "snow_cover_tab": "Niva e glassa",
        "glacier_tab": "Glatschers",
        "temperature_tab": "Clima",
        "permafrost_tab": "Sil parmanen congla e sil",
        "biodiversity_tab": "Diversitad da vidas",
        "economic_tab": "Impactus economics",
        "causes_label": "Causas e context",
        "anthropogenic_label": "Factors umans",
        "ecological_label": "Resultats ecologics",
        "social_label": "Tge che quai significa",
        "copy_btn": "Copiar a appunts",
        "report_btn": "Generescha rapport cumpleit",
        "map_title": "Maupa da perdittas da glatschers alpins",
        "demo_mode_label": "📍 Modus demo activ — utilisaziun da datas precargadas",
        "language_select_label": "Lingua",
        "region_select_label": "Regiun alpina",
        "year_range_label": "Perioda d'ons",
        "data_sources_label": "Fontaunas da datas",
        "about_label": "Davart AlpineCheck",
        "supported": "Sustinut",
        "contradicted": "Contradît",
        "partially_supported": "Parzialmain sustinût",
        "glaciers_lost": "Superfitsch da glatscher perditga",
        "temp_rise": "Gradient da temperatura",
        "snow_days_lost": "Dis da cuorta da niva perditga",
        "permafrost_degrading": "Sil parmain congla in degradaziun",
    },
    "hr": {
        "app_title": "⛰ AlpineCheck",
        "app_subtitle": "Satelitska klimatska obavijest za alpske novinarima",
        "input_placeholder": "Postavite pitanje ili podnesi tvrdnju o alpskoj klimi...",
        "mode_query_label": "Režim upita — odgovor na vaše pitanje",
        "mode_validation_label": "Režim provjere — provjera vaše tvrdnje",
        "analyze_btn": "Analiziraj",
        "verdict_label": "Presuda",
        "confidence_label": "Povjerenje",
        "key_stat_label": "Ključna statistika",
        "summary_label": "Sažetak",
        "sources_label": "Izvori i kredibilitet",
        "credibility_label": "Procjena kredibiliteta",
        "accurate_finding_label": "Tačan nalaz",
        "snow_cover_tab": "Snijeg i led",
        "glacier_tab": "Ledenjaci",
        "temperature_tab": "Klima",
        "permafrost_tab": "Trajni mraz i tlo",
        "biodiversity_tab": "Biološka raznolikost",
        "economic_tab": "Ekonomski utjecaj",
        "causes_label": "Uzroci i kontekst",
        "anthropogenic_label": "Ljudski čimbenici",
        "ecological_label": "Ekološki utjecaji",
        "social_label": "Što to znači",
        "copy_btn": "Kopiraj u međuspremnik",
        "report_btn": "Generiraj potpuni izvještaj",
        "map_title": "Karta gubitka alpskih ledenjaka",
        "demo_mode_label": "📍 Demo način aktivan — korištenje učitanih podataka",
        "language_select_label": "Jezik",
        "region_select_label": "Alpska regija",
        "year_range_label": "Raspon godina",
        "data_sources_label": "Izvori podataka",
        "about_label": "O AlpineCheck",
        "supported": "Podržano",
        "contradicted": "Osporeno",
        "partially_supported": "Djelomično podržano",
        "glaciers_lost": "Izgubljena površina ledenjaka",
        "temp_rise": "Porast temperature",
        "snow_days_lost": "Izgubljeni dani snježnog pokrova",
        "permafrost_degrading": "Degradacija trajnog mraza",
    },
    "fur": {
        "app_title": "⛰ AlpineCheck",
        "app_subtitle": "Inteligjenzie climatiche alimentade di satelit pai giornalists alpins",
        "input_placeholder": "Fâ une domande o presente une afirmaziun su la climz alpine...",
        "mode_query_label": "Modalitâ ricerche — rispuindi a la tô domande",
        "mode_validation_label": "Modalitâ validaziun — controle la tô afirmaziun",
        "analyze_btn": "Analiza",
        "verdict_label": "Verdut",
        "confidence_label": "Confidanze",
        "key_stat_label": "Statiste clavê",
        "summary_label": "Somari",
        "sources_label": "Fonts e credibilitât",
        "credibility_label": "Valutaziun di credibilitât",
        "accurate_finding_label": "Risultât esât",
        "snow_cover_tab": "Nev e ghiaç",
        "glacier_tab": "Giaciârs",
        "temperature_tab": "Climat",
        "permafrost_tab": "Permafôst e tiere",
        "biodiversity_tab": "Biodiversitât",
        "economic_tab": "Impat economichis",
        "causes_label": "Cauzis e contest",
        "anthropogenic_label": "Factors umans",
        "ecological_label": "Risultats ecologjics",
        "social_label": "Tandi al significât",
        "copy_btn": "Copie in bufar",
        "report_btn": "Genere raport complet",
        "map_title": "Mape de perde dai giaciârs alpins",
        "demo_mode_label": "📍 Modalitâ demo ative — datis precarjis",
        "language_select_label": "Lenghe",
        "region_select_label": "Regjun alpine",
        "year_range_label": "Interval di agns",
        "data_sources_label": "Fonts di datis",
        "about_label": "Tanding a AlpineCheck",
        "supported": "Sofuartît",
        "contradicted": "Contradît",
        "partially_supported": "Part sostinut",
        "glaciers_lost": "Superfice dai giaciârs perdue",
        "temp_rise": "Ament de temperature",
        "snow_days_lost": "Zencs di copierte di nev perdutz",
        "permafrost_degrading": "Degradaziun dal permafôst",
    },
}

# Scientific glossary in all languages
SCIENTIFIC_GLOSSARY = {
    "glacier": {
        "en": "Large persistent body of ice and snow that flows downslope under gravity",
        "de": "Großer persistenter Körper aus Eis und Schnee, der unter Schwerkraft abwärts fließt",
        "fr": "Large masse persistante de glace et de neige s'écoulant en aval sous la gravité",
        "it": "Grande massa persistente di ghiaccio e neve che scorre verso il basso sotto la gravità",
        "sl": "Velika trajnajoče masa ledu in snega, ki teče navzdol pod vplivom gravitacije",
        "rm": "Grond corp persistent d'atgliez e niva che fluiva sut cuntuorn",
        "hr": "Velika trajna masa leda i snijega koja teče niz nagib pod utjecajem gravitacije",
        "fur": "Masse grandt e durabile di ghiaç e nev che fluia in cale sut la fuarze di gravidât",
    },
    "NDSI": {
        "en": "Normalized Difference Snow Index - satellite metric measuring snow presence (0=no snow, 1=pure snow)",
        "de": "Normalisierter Differenzschneeindex - Satellitenmesswert zur Erfassung von Schneebestand",
        "fr": "Indice de Différence Normalisée de la Neige - mesure satellitaire de la présence de neige",
        "it": "Indice di Differenza Normalizzata della Neve - misura satellitare della presenza di neve",
        "sl": "Normaliziran različni indeks snega - satelitska meritev prisotnosti snega",
        "rm": "Indice Normalisà da Differenza da Niva - mesurada satellit da la presenzia da niva",
        "hr": "Normalizirani indeks razlike snijega - satelitska mjera prisutnosti snijega",
        "fur": "Indis di diferenze normalizà da nev - misurade satelit de la presenze di nev",
    },
    "albedo": {
        "en": "Fraction of sunlight reflected by a surface (snow has high albedo, glaciers lower)",
        "de": "Anteil des von einer Oberfläche reflektierten Sonnenlichts",
        "fr": "Fraction de la lumière solaire réfléchie par une surface",
        "it": "Frazione della luce solare riflessa da una superficie",
        "sl": "Delež sončne svetlobe, ki se odbije od površine",
        "rm": "Fracziun da sulegl rifletü d'ina superficie",
        "hr": "Udio sunčeve svjetlosti koji se odbija od površine",
        "fur": "Fraze de lus dal sole rifletude da une superficie",
    },
    "permafrost": {
        "en": "Ground that remains frozen for at least two consecutive years",
        "de": "Boden, der mindestens zwei aufeinanderfolgende Jahre gefroren bleibt",
        "fr": "Sol qui reste gelé pendant au moins deux ans consécutifs",
        "it": "Terreno che rimane congelato per almeno due anni consecutivi",
        "sl": "Tla, ki ostanejo zmrznjena najmanj dve zaporedni leti",
        "rm": "Tiera che resta cunglas per omnimain dus ons consecutivs",
        "hr": "Tlo koje ostaje zamrznjeno najmanje dvije uzastopne godine",
        "fur": "Tiere che reste congle par omnimancul dôs agns consecutîfs",
    },
    "snow_cover": {
        "en": "Area or duration of ground covered by snow at any time",
        "de": "Bereich oder Dauer der Schneebedeckung am Boden",
        "fr": "Zone ou durée du sol couvert de neige à tout moment",
        "it": "Area o durata del terreno coperto da neve in qualsiasi momento",
        "sl": "Območje ali trajanje tal pokritih s snegom v kateremkoli času",
        "rm": "Area u durada da terreno cuvert da niva",
        "hr": "Područje ili trajanje tla prekrivenog snijegom u bilo kojem trenutku",
        "fur": "Area u durade da terie cuarte da nev",
    },
    "anomaly": {
        "en": "Deviation from the long-term average (baseline) for a variable",
        "de": "Abweichung vom langfristigen Durchschnitt (Basislinie) für eine Variable",
        "fr": "Écart par rapport à la moyenne à long terme (valeur de référence) pour une variable",
        "it": "Deviazione dalla media a lungo termine (linea di base) per una variabile",
        "sl": "Odstopanje od dolgoročnega povprečja (izhodičča) za spremenljivko",
        "rm": "Deviziun dal media a lung termin (basala) per ina variabla",
        "hr": "Odstupanje od dugoročnog prosjeka (bazna linija) za varijablu",
        "fur": "Deviaziun dal media a lung termin (basale) par une variabile",
    },
    "baseline": {
        "en": "Reference period (typically 1980-2010 or historical average) used for comparison",
        "de": "Referenzzeitraum zur Vergleichbarkeit",
        "fr": "Période de référence utilisée pour la comparaison",
        "it": "Periodo di riferimento utilizzato per il confronto",
        "sl": "Referenčno obdobje, uporabljeno za primerjavo",
        "rm": "Perioda da referenza utilisada per comparaziun",
        "hr": "Referentno razdoblje korišteno za usporedbu",
        "fur": "Periude di referinze utilizade par confronto",
    },
    "phenology": {
        "en": "Timing of seasonal biological events (e.g., plant blooming, animal migration)",
        "de": "Zeitliche Abstimmung saisonaler biologischer Ereignisse",
        "fr": "Synchronisation des événements biologiques saisonniers",
        "it": "Sincronizzazione degli eventi biologici stagionali",
        "sl": "Čas pojava sezonskih bioloških dogodkov",
        "rm": "Temprada da eventualitads biologicas stagiunals",
        "hr": "Vremenski raspored sezonskih bioloških događaja",
        "fur": "Temperade dai eventualitats biologichis stagiunâls",
    },
    "mass_balance": {
        "en": "Annual change in glacier mass from accumulation minus ablation (mm water equivalent)",
        "de": "Jährliche Änderung der Gletschermasse",
        "fr": "Changement annuel de la masse glaciaire",
        "it": "Cambio annuale della massa glaciale",
        "sl": "Letna sprememba ledenikove mase",
        "rm": "Midada anuala da la massa da glatscher",
        "hr": "Godišnja promjena ledeničke mase",
        "fur": "Midade anuala de la masse dal giaciâr",
    },
    "moraine": {
        "en": "Unconsolidated rock and debris deposited by glacial action",
        "de": "Von Gletschertätigkeit abgelagertes Gestein und Trümmermaterial",
        "fr": "Roche et débris non consolidés déposés par l'action glaciaire",
        "it": "Roccia e detriti non consolidati depositati dall'azione glaciale",
        "sl": "Nekonsolidirana kamnina in ruševina odložena s poledenjem",
        "rm": "Silt e detri deposità da l'acziun da glatscher",
        "hr": "Nekonsolidirana stijena i detritus odloženi glacijalnom radnjom",
        "fur": "Silt e detri depositutz da l'aziun dai glaciârs",
    },
}

def t(key: str, lang: str) -> str:
    """Translate UI string key to target language."""
    if lang not in UI_STRINGS:
        lang = "en"
    if key in UI_STRINGS[lang]:
        return UI_STRINGS[lang][key]
    # Fallback to English
    return UI_STRINGS["en"].get(key, key)

def detect_language(text: str) -> str:
    """Detect language from text using langdetect."""
    try:
        detected = langdetect.detect(text)
        # Map detected language codes to our supported languages
        lang_map = {
            "en": "en", "fr": "fr", "de": "de", "it": "it",
            "sl": "sl", "rm": "rm", "hr": "hr", "fur": "fur"
        }
        return lang_map.get(detected, "en")
    except:
        return "en"

def get_glossary_term(term: str, lang: str) -> str:
    """Get scientific glossary term definition in target language."""
    if lang not in SCIENTIFIC_GLOSSARY.get(term, {}):
        lang = "en"
    return SCIENTIFIC_GLOSSARY.get(term, {}).get(lang, term)
